### ISSUE TITLE
Versions of postal.js, federation and federation.xframe that work together

### ISSUE THREAD

**Issue by keirlawson** [postaljs/postal.js#109]
I'm struggling to get these components working together, can anyone recommend versions which will work well together?

**Comment by ifandelse** [comment]
@snowball Sorry you're having issues getting them to work together (and apologies for the delayed response...been super busy). I'll see if I can't put together some compatibility notes for you.

**Comment by ifandelse** [comment]
@snowball The versions specified in the latest xframe check out OK:

* postal.federation >=0.2.4
* postal.xframe v0.3.2
* postal ~0.11.2 (though I've tested it from 0.11.2 up to 1.0.0 and all worked)

One thing to note, the latest postal (v1.0.0) updated the lodash dep to 3.1.0, so if you use bower, you're safe to resolve the lodash deps to 3.1.0 for all three postal-related libs above.

What versions are you trying? Perhaps if I know that, I can be of better assistance....

**Comment by snowball** [comment]
I was struggling to get federation and xframe working with 0.12.4 but I dropped to 0.11.2 and got everything working nicely with the versions just as you suggest :)
