### ISSUE TITLE
Question: Would you be willing to host a version of Postal that uses the modular version of Lodash?

### ISSUE THREAD

**Issue by aintnorest** [postaljs/postal.js#111]
I have a modified version of postal that I use that uses the modular version of lodash. I use lodash in my applications but rarely use enough of it that I feel like pulling in the entire library is worth while. Would you mind putting together an npm version of postal that uses the modulized version for dep. Or mind if I do?

**Comment by Daveawb** [comment]
See https://github.com/postaljs/postal.js/pull/110

**Comment by jdalton** [comment]
See https://github.com/postaljs/postal.js/issues/91#issuecomment-73159144.

**Comment by ifandelse** [comment]
Done! :smiley_cat: See [#91 (comment)](https://github.com/postaljs/postal.js/issues/91#issuecomment-73399021).
