### ISSUE TITLE
Wiki docs refer to deprecated methods

### ISSUE THREAD

**Issue by netaisllc** [postaljs/postal.js#114]
**v0.11.0** deprecated several **SubscriptionDefinition** methods, replacing them with methods of other names. Yet the __Wiki__ refers to the older names. 

Would you accept a PR to cure?

**Comment by ifandelse** [comment]
@netaisllc Sure! I can't remember, but GitHub might allow you to edit the wiki directly if you see an Edit button at the top right. Thanks! :smile:

**Comment by netaisllc** [comment]
"So it was written, so it was done". 
Good idea; All cleaned up. Thanks for a great project.

**Comment by ifandelse** [comment]
Thank you very much @netaisllc!
