### ISSUE TITLE
exceptions in subscription callbacks

### ISSUE THREAD

**Issue by eapearson** [postaljs/postal.js#115]
Hi,
I've enjoyed using postal, and it has been very helpful.

I thought there must be an error handler mechanism for subscriptions, because without such one has to handle exceptions with a try .. catch within the callback. Otherwise, an exception stops the queue and crashes the interpreter. I see that there is a mechanism in place to handle catching exceptions within the handler, but it does not appear to be used in the execution of subscription callbacks.

Perhaps I'm overlooking how to invoke this. I tried setting up a subscription using a catch: property in addition to the callback: but that didn't work, and a brief inspection of the code did not reveal how catch actually could be invoked because the setup of a subscription doesn't seem to call the catch method.

Typically I use the chained method of setting up subscriptions (postal.channel.subscribe), so having a second callback argument to handle errors, or extending the subscription object to accept chained requests like
postal.channel.subscribe.callback.catch
or even
postal.channel.subscribe.topic.on(success, error)
would be awesome.

Additionally, it would be very helpful to be able to install both a global error handling mechanism and perhaps by channel. It is not good if a single bad subscription can crash an app. I would like to be able to protect the app from bad subscriptions with a global handler, and also be able to specify more specify behavior at the subscription and perhaps channel level.

Thanks,
Erik.

**Comment by ifandelse** [comment]
@eapearson Thanks so much for the heads up on `catch` not seeming to be invoked. It's quite possible I've inadvertently broken it recently, so I will definitely look into that. I'm open to adding a global error handling option that you can opt into (though I'd document it with some warnings, given that try/catch can be expensive in JS). I'll keep you posted on what I find, thanks!

**Comment by ifandelse** [comment]
@eapearson In case this is still an issue for you, wanted to follow up and say that I've verified that calling `.catch( errorHandlerFn )` on a subscription definition worked as expected. Just be aware that opting into a try catch will introduce some level of performance decrease (though it may not even be noticeable depending on what you're doing). Thanks!

**Comment by TeNNoX** [comment]
It is not possible to catch on the channel definition, is it?
Like that there is some way to prevent a broken subscription to stop the event from reaching the other subscribers?
