### ISSUE TITLE
Removing all Subscriptions

### ISSUE THREAD

**Issue by lucastschmidt** [postaljs/postal.js#116]
Guys, when an object needs to die, we need to remove subscriptions.

Is is possible to have a function to remove all subscriptions, or is this technically not possible or "morally" wrong?

Currently, we have to store subscriptions, and before object dies, all subscriptions must be unsubscribed.

Or, does anyone have any hack/tips regarding this?

**Comment by ifandelse** [comment]
Hi @lucastschmidt, you have a few options, depending on the need.

If you need to clear *all* subscriptions (this clears everything): `postal.reset();`

The `postal.unsubscribe` method can take 1-to-n subscriptions:
```javascript
postal.unsubscribe(sub1, sub2, sub3);
```

You can also call `postal.unsubscribeFor()`:

```javascript
postal.unsubscribeFor({ channel: "someChannel", topic: "some.topic" });
```

`unsubscribeFor` also supports checking the context and other props you add to your subscription:

```javascript
// fake example object to use as a context
var someObj = {};
var sub = postal.subscribe({ channel: "someChannel", topic: "some.topic", callback: function() {})
                         .context( someObj );

// you can call unsubscribe and pass in the context prop on the options:
postal.unsubscribeFor({ context: someObj });

// this works for other props you add
sub.someCustomValue = 12345;
postal.unsubscribeFor({ someCustomValue: 12345 });
```

**Comment by lucastschmidt** [comment]
Got it, thanks. There are basically no way for me to do something like, postal.unsubscribe(someObj), and remove that object from subscribers. 

I already adapted my code, to store list of subscriptions, so I can clean it up. 

Thanks for the quick answer!

**Comment by ifandelse** [comment]
@lucastschmidt actually, assuming I follow you correctly, the second to last example above does that. If the object you want to pass has been used as the context of the subscriptions, passing it as `postal.unsubscribeFor({ context: someObj });` removes all the subscriptions where that object was set as the context of the subscription callback. The `unsubscribe` method expects a subscription definition (or an args list of subscription definitions), so postal wouldn't know what to do with a non subscription definition object passed to that.

**Comment by lucastschmidt** [comment]
@ifandelse got it, thanks.
