### ISSUE TITLE
Listen to all messages within a channel?

### ISSUE THREAD

**Issue by drcharris** [postaljs/postal.js#117]
I'm trying to write a simple bridge from a Postal channel to a socket.io socket (with the eventual aim of adding a light durability/queueing feature). I want to subscribe to all messages within the channel but simply using a wildcard topic of `'*'` doesn't seem to match topics that contain `'.'` characters.

Is there a way to blanket subscribe at the channel level? I suppose I could add a wiretap at the global level and filter but was hoping for something a bit more elegant.

**Comment by drcharris** [comment]
Never mind - I over-rode the resolver compare function, works nicely.

**Comment by ifandelse** [comment]
@drcharris - in this case you won't need to override the resolver compare function. The README explains there are two wildcard characters, `*` and `#`. These work like AMQP's approach to topic bindings in server side message. `*` only matches on "word" in a period-delimited topic, where `#` matches 0-n. See https://github.com/postaljs/postal.js#subscribing-to-a-wildcard-topic-using--1.

**Comment by drcharris** [comment]
Thanks, I was aware of the use of `*` and `#`, but the standard compare fn seems to only work for individual sections of a period-delimited structure. If I want to capture any possible topic this fails - `*` captures topic `'a'` but not topic `'a.b'`, for instance (I would need to subscribe with `*.*` for that). Below sample shows that behaviour.

```javascript
var postal = require('postal');

var channel = postal.channel('test');
var sub = postal.subscribe({
	channel:'test',
	topic: '*', //captures 'a', use *.* for a.b, *.*.* for a.b.c
	callback: (msg, envelope) => {
		console.log(envelope.topic);
	}
});

channel.publish('a', {});
channel.publish('a.b', {});
channel.publish('a.b.c', {});
```
But, not a big problem. I just used a RegExp compare fn instead, works nicely.

**Comment by ifandelse** [comment]
@drcharris If you need to match any topic on a channel, regardless of topic hierarchy length, use `#`. See [this](http://jsfiddle.net/aao352z9/). The built-in resolver covers the use-case you're describing

**Comment by drcharris** [comment]
That's what I get for not reading the doc properly - my bad. Thanks!
