### ISSUE TITLE
isArray is not defined in postal.lodash.js

### ISSUE THREAD

**Issue by hankhsiao** [postaljs/postal.js#122]
This could be a problem, please check.
https://github.com/postaljs/postal.js/blob/master/lib/postal.lodash.js#L619

**Comment by ifandelse** [comment]
Looks like there's an edge case where if `__postalReady__` is defined and postal tried to process the contents, the mindash version of postal will have an issue. I'm in the process of converting this project's build and module format, and plan to replace lodash methods with ES5 equivalents where possible, to minimize dependency footprint....I'll address this with those changes, thanks!
