### ISSUE TITLE
postal.observe plugin

### ISSUE THREAD

**Issue by yamalight** [postaljs/postal.js#127]
Hey! Didn't know where else to write about it, so I'll just open this ticket here.
I'd created a small postal plugin called "postal.observe" that we use in some of our projects.
It wraps postal.subscribe into [Rx.Observable](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/observable.md) which allows doing a variety of reactive trasformations on messages, e.g.: 
```js
postal.observe({channel: 'dataFromServer', topic: 'blogPosts'})
.filter((data) => data.date > yesterday)
.map((data) => data.text)
.subscribe((text) => $('body').append(text));
```

Thought you might be interested (and maybe would want to add it to plugins list :)).
The plugin is open sourced under MIT license [on GitHub](https://github.com/yamalight/postal.observe).

**Comment by ifandelse** [comment]
@yamalight Cool! Curious as to the kind of use-case you're using this in. I'll definitely get the plugin list updated to include this.

**Comment by yamalight** [comment]
@ifandelse we have an app that handles stream of data from server. It needs to render this stream in various UI component in a slightly different ways (so, some transformations are applied to data).

E.g. we have a thing that renders entities that have locations on map. Before Rx we just used callback approach which worked fine, but was a bit ugly. Now it's just:
```js
dataChannel.observe('data')
.filter((it) => it.location)
.map((it) => it.location)
.subscribe((location) => this.setState({location}));
```
Way cleaner IMO :)
And when needed we get throttling and timeouts out of the box, which is nice as well (we have some components that aggregate data and should only update every couple of seconds).

**Comment by ifandelse** [comment]
@yamalight nice! Sounds like a pretty neat solution.
