### ISSUE TITLE
Browser compatibility and performance docs

### ISSUE THREAD

**Issue by noherczeg** [postaljs/postal.js#129]
Hi!

If I'm not mistaken the documentation (really nice one) does not talk about the browser compatibility of your lib. Would it be possible to at least inform people about the required ES version and/or a few words about what polyfills are needed to use it if let's say it doesn't support ES3?

Lastly: this might be a really dumb question, but the lib isn't really small, I totally see that it only runs in memory, but could you provide some information about it's performance? I'm seriously considering to drop angular from our current project for several reasons and I'm also considering to use this for messaging, but I'd like to gather some info about this topic as well :)

I think that it would be really nice to write about these in the docs because others might be interested as well!

Thanks again!

**Comment by ifandelse** [comment]
Hi @noherczeg. I apologize for the long delay in replying. I used to have some perf tests on jsperf, but have been unable to find them to update them (it's an endless cycle of captchas now, sadly). I added a simple publish perf test via [jslitmus](https://code.google.com/p/jslitmus/), which you can see here: <http://postaljs.github.io/postal.js/perf.html>

It gives you output along these lines....

![image](https://cloud.githubusercontent.com/assets/197026/10036824/16f0166a-617b-11e5-8d9b-be5d35373eaa.png)

FWIW, a few versions back I spent a great deal of time tweaking and improving performance (focusing on better internal data structure/caching to make subscription lookups more performant) - I was pretty happy with the results (though I know the optimization tasks _never_ end!). :smile:
