### ISSUE TITLE
Envelopes need to be covered more in the Documentation

### ISSUE THREAD

**Issue by r4j4h** [postaljs/postal.js#130]
The documentation is very nice and makes mention of envelopes and how they ensure message data always comes with an expected format, but the examples never really showed this in practice. Additionally, while the structure of the envelopes is hinted at...

> contains metadata about the message like the channel, topic, timestamp and any other data which might have been added by the sender

... it is never explicitly described.

I think this is potentially one of postal.js's strongest points and should be advertised more heavily. :)

**Comment by ifandelse** [comment]
@r4j4h Thanks so much for the feedback. I will try and take some time this week to update the docs to better explain envelopes :smile:

**Comment by r4j4h** [comment]
My pleasure. I am excited to see the what you come up with! =) And thank you for the quick response!

**Comment by ifandelse** [comment]
@r4j4h Banged some stuff out while on a road trip: https://github.com/postaljs/postal.js/wiki/Envelopes 
If you get a sec, check that out and see if that is along the lines of what you were looking for.... thanks!

**Comment by r4j4h** [comment]
Wow, great job!! That is pretty much exactly what I was looking for! =)
