### ISSUE TITLE
i made you a logo

### ISSUE THREAD

**Issue by derickbailey** [postaljs/postal.js#132]
cause i wanted to... and cause this project is awesome and needs a logo, even if the logo is terrible :D

http://cloud.derickbailey.com/image/1C2S0S0t3T0t

![](https://s3.amazonaws.com/f.cl.ly/items/2D3t0a1X0w35161H2I0l/postaljs.png)

**Comment by derickbailey** [comment]
or this!

http://cloud.derickbailey.com/image/3E100L3F0i3t

![](https://s3.amazonaws.com/f.cl.ly/items/2I1o0y46392P3F3X3o3g/postaljs2.png)

**Comment by ifandelse** [comment]
@derickbailey :tada: :tada:  Sweet! I really like the second one :smile: The JS stamp was a nice touch. Seriously - this is greatly appreciated. I'm _awful_ at visual design of anything (except for maybe ice cream sundaes), and it's truly sad postal has gone so long without a logo. You want me to download from the link above? Or work from a diff file?

**Comment by rauhryan** [comment]
Nice! 

Agreed! One of my all time favorite js libraries

**Comment by derickbailey** [comment]
oh, how does this one look?

tried to make the "postal" stand out more, and reduced the stamp size

![](https://s3.amazonaws.com/f.cl.ly/items/3o3D0T2w1s0K1W1y2r2O/postaljs2.png)

**Comment by ifandelse** [comment]
@derickbailey seriously - I'm speechless! Thank you!! :smile_cat:

**Comment by dcneiner** [comment]
This is awesome!!! 



—

**Comment by derickbailey** [comment]
Ok, for reals last edits. I realized I had the wrong yellow and black for the JS stamp. fixed that, and made the POSTAL word stand out more. :)

![](https://s3.amazonaws.com/f.cl.ly/items/1f2H2U3N1J0n2V0k3q3v/postaljs.jpg)

https://www.dropbox.com/s/ozsv24x130m8gqo/postaljs-logo.zip?dl=0 (should be the same download link, i think)

**Comment by derickbailey** [comment]
see PR #133

**Comment by SuperMariolle** [comment]
Hi!
Can I use your picture in a thesis? Thanks!
