### ISSUE TITLE
can postal.js use with requirejs? how? 

### ISSUE THREAD

**Issue by dyh333** [postaljs/postal.js#135]
can postal.js use with requirejs? how?

**Comment by alanmacleod** [comment]
I just added it like any other module. Postal adds itself to the document global so it only creates one shared instance across all of your modules that include it

**Comment by ifandelse** [comment]
@dyh333 - yes, postal is wrapped in a [UMD](https://github.com/umdjs/umd), which means it should work in CommonJS, AMD and plain "browser global" scenarios. One of the examples in the repo loads it via require.js, see this: https://github.com/postaljs/postal.js/tree/master/example/amd
