### ISSUE TITLE
Uncaught TypeError: Cannot read property 'postal' of undefined

### ISSUE THREAD

**Issue by geros** [postaljs/postal.js#136]
Hi, 
I am trying to use postal.js alongside machina a using babel and browserify but i get this error when i do : 
```sh
import {postal} from '../../../../node_modules/postal/lib/postal.lodash';
```

this happens when it tries to run 
```sh
( this, function( _, global, undefined )
```

after module definition 

```sh

	if ( typeof define === "function" && define.amd ) {
		// AMD. Register as an anonymous module.
		define( function() {
			return factory( _, root );
		} );
	
	} else if ( typeof module === "object" && module.exports ) {
		// Node, or CommonJS-Like environments
		module.exports = factory( _, this );
	} else {
		// Browser globals
		root.postal = factory( _, root );
	}
}( this, function( _, global, undefined ) {
```
Obviously the global var is not exposed
Do you have any clue on that ? 

Thanks

**Comment by xyleen** [comment]
So to say, the easiest way to reproduce is:
``` javascript
var postal = require('postal');
```
and run it like:
`node --use_strict test`

Produces the same error:
```
/home/test/node_modules/postal/lib/postal.js:25
        var prevPostal = global.postal;
                               ^
TypeError: Cannot read property 'postal' of undefined
    at /home/test/node_modules/postal/lib/postal.js:25:25
    at prevPostal (/home/test/node_modules/postal/lib/postal.js:19:20)
    at Object.<anonymous> (/home/test/node_modules/postal/lib/postal.js:24:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/test/test.js:18:14)
```

**Comment by sleepingevil** [comment]
I have the exact same issue when running my code thourgh babel's es2015 preset.
    ...
    var postal = require("postal");
    ...

after that I'm running it though babel like this:

    ...
    babel script.js > build/script.js --presets es2015 
    ...

Opening the site in a browser is giving me the following error: 

> Uncaught TypeError: Cannot read property 'postal' of undefined

The error is reported from here:

    ( function( root, factory ) {
    	...
    }( this, function( _, global, undefined ) {
    	var prevPostal = global.postal;  <<-- FROM HERE
    	var _defaultConfig = {
    ...

**Comment by cestrensem** [comment]
Same problem then I running "karma" tests:
```
PhantomJS 1.9.8 (Windows 8 0.0.0)
TypeError: 'undefined' is not an object (evaluating 'global.postal')
at http://localhost:8081/base/spec/index.js?36a9afec145c61807dba2e6f6d5cc33f9b115b8d:9622``
```

**Comment by entrodus** [comment]
In my case i was manually referencing postal.js lodash.postal.js in a asp.net mvc environment. Turns out i had to reference a full version of lodash instead of lodash.postal.js.
