### ISSUE TITLE
Request typescript definitions

### ISSUE THREAD

**Issue by on3al** [postaljs/postal.js#137]

**Comment by ifandelse** [comment]
@barticus [took a stab at this](https://github.com/postaljs/postal.js/pull/98), but unfortunately right around the time I was making some big changes internally (and some breaking changes to the API, IIRC). Typescript isn't anything my team is using on a daily basis, so it hasn't been a priority. I'm open to contribution along these lines, but I'd hold off until I get the build & module format updated and have converted the project to use less of lodash.
