### ISSUE TITLE
Demo does not work due to postal.js library not being found

### ISSUE THREAD

**Issue by JosephWoodward** [postaljs/postal.js#138]
The [demo](http://jsfiddle.net/ifandelse/8dLpkpcf/) linked within the read me no longer works. Having had a quick look, it appears that it's because the reference the library (https://rawgit.com/ifandelse/postal.js/conduit-ectomy/lib/postal.js) is no longer found and results in a 404 error.

**Comment by ifandelse** [comment]
Sorry @JosephWoodward (for the broken link and long overdue response). This is updated in the master branch now.
