### ISSUE TITLE
Replace some lodash modules with ES5?

### ISSUE THREAD

**Issue by philmander** [postaljs/postal.js#140]
I'm embedding postal.js in a Browserify build and I want to minimize the dependencies it pulls in.

I noticed many of the lodash modules it uses could be replaced with their equivalent ES5 methods ([a quick google explains in more depth if you need it](http://itsnull.com/articles/start-using-es5/))

If I create a PR with some lodash to ES5 updates, would you consider merging, or is there more to this than meets the eye?

**Comment by ifandelse** [comment]
@philmander sincere apologies for taking SO long to reply!! This is actually something I'm working on (along with updating the overall build and module format, etc.). I'm hopeful that I can wrap things up with the changes during the holiday break.
