### ISSUE TITLE
Subscription with .defer()

### ISSUE THREAD

**Issue by escar** [postaljs/postal.js#141]
Hi,

I was having a situation where a subscribe was being executed multiple times, when it should be only one. After add .defer() option to the subscription (or .delay(0)), the problem stopped happening.

I cannot understand exactly why. Can somebody help?

Thanks

**Comment by pinoniq** [comment]
Can you provide some code that triggers this error? Or steps to reproduce?
Hard to debug when we do not have a way to reproduce?

**Comment by ifandelse** [comment]
Sorry for long overdue reply here @escar - if you have an example we could look at that reproduces the issue, could you send the link?

**Comment by ifandelse** [comment]
Closing for now - but happy to re-open if this is still an issue for you.
