### ISSUE TITLE
Postal 1.0.11 is overring lodash used version

### ISSUE THREAD

**Issue by germanrcuriel** [postaljs/postal.js#153]
Hi!

First of all thanks all for working in this great tool :)

I just want to warn you that the new release of postal.js (`1.0.11`) is overriding the `window._` and I guess this is something that you don't want to do, right?

UPDATE: We are using this library in a frontend application with browserify and using a 3.x version of lodash, and after updating to `postal@1.0.11` we got `lodash@4.11.1`.

Thanks! :)

**Comment by ifandelse** [comment]
@germanrcuriel - terribly sorry for the delay in replying. We've run into the same issue - and I think lodash itself is overwriting `window._` - though I'm about to look into using `_.noConflict()` to see if I can work around this issue. I'll keep you posted, thanks!

**Comment by germanrcuriel** [comment]
No worries ;-)

**Comment by ifandelse** [comment]
@germanrcuriel I believe I have this taken care of. Let me know if you run into other issues. Thanks!
