### ISSUE TITLE
Broken postal.lodash.js

### ISSUE THREAD

**Issue by thibthib** [postaljs/postal.js#154]
Since the lodash@4 version bump in the postal@1.0.9 update, the postal.lodash.js build is broken. As shown in the `npm run test-lodash` : 
```bash
❯ npm run test-lodash

> postal@2.0.0 test-lodash /Users/thibaut/Code/postal.js
> ./node_modules/mocha/bin/mocha -r spec/helpers/node-lodash-build-setup.js spec

module.js:440
    throw err;
    ^

Error: Cannot find module 'lodash/internal/createPartialWrapper'
```

After some investigation, it seems that the `src/mindash.js` is out of date, as lodash@4.0.0 changed most of its modules paths (the full list of changes is here : https://github.com/lodash/lodash/wiki/Changelog#v400)

For example 
```js
var createPartialWrapper = require( "lodash/internal/createPartialWrapper" );
```
seems to be now
```js
var createPartialWrapper = require( "lodash/_createPartialWrapper" );
```

For people using Webpack or other bundlers with the postal.lodash.js build, I recommend to keep the postal version to 1.0.8 until this is fixed.

**Comment by thibthib** [comment]
I wanted to submit a PR until the simple `require( "lodash/internal/createForEach" )` transformation into  `require( "lodash/_createForEach" )` failed, as this module don't seem to exist anymore.

**Comment by jcreamer898** [comment]
Something is definitely up, a bunch of my builds are failing right now from this.

**Comment by jcreamer898** [comment]
Looks like the only way to "fix" it as of right now is to lock the version of lodash to 3.x.
