### ISSUE TITLE
Postal 2.0.3: _.noConflict() unbinds lodash from window

### ISSUE THREAD

**Issue by scottaj91** [postaljs/postal.js#159]
I added postal.js 2.0.3 to our app which already relies heavily on lodash.

After loading postal the app no longer works as lodash has been unbound from window._ due to the call to _.noConflict() when postal is loaded.

The change was introduced here: d9bd448ea0853fb8d93b0efd398e7985c167b131.

(PS: I hope I've not misunderstood something basic!)

**Comment by ifandelse** [comment]
@scottaj91 apologies for the headache on this. I will look into it and get a fix up.

**Comment by scottaj91** [comment]
@ifandelse Brilliant. Much appreciated. Have reverted to 2.0.0 for now.

**Comment by ifandelse** [comment]
@scottaj91 give v2.0.4 a shot and let me know if that clears things up for you.

**Comment by scottaj91** [comment]
Yeah the conditional guard you put in has fixed the issue for our app. Thanks for the quick turnaround! :)
