### ISSUE TITLE
Request : Nuget Package Update & DefinitelyTyped for TypeScript

### ISSUE THREAD

**Issue by martooooo** [postaljs/postal.js#81]
Firstly, Thanks very much for this great utility.

We noticed that the postal.js stays at version 0.90 on nuget.org. It will be great to have it updated to the latest.

The other thing we are wondering is if we can have a DefinitelyTyped file which will enable the postal.js to run under TypeScript language --- there is a growing trend of combination of angular.js & typescript, which brings Object Oriented power to angular. We assume there will be a bunch of guys who will need this cool utility running under TypeScript.

Best Wishes

**Comment by shumy** [comment]
I subscribe on this. Where is the postal.d.ts ? Didn't find it on DefinitelyTyped ?

**Comment by ifandelse** [comment]
@shumy Unfortunately I don't have the bandwidth at the moment to get a type definition for the current version of postal (I was in the middle of a few breaking changes at the time the original PR was submitted). I'm certainly open to the original PR being updated with a type def that's current, etc., I just know that it would be a while before I could get to it myself.
