### ISSUE TITLE
Replace complete lodash with partial includes to reduce size

### ISSUE THREAD

**Issue by yamalight** [postaljs/postal.js#91]
So, here's my case: I use postal.js as a messaging library for a set of components I have.
Components are CommonJS modules and assembled into the app using [browserify](http://browserify.org/).
Which means my messaging is set up using postal from npm, which again means that postal includes the whole lodash as a dependency (which is ~50kb minified).

It would be good to be able to use lodash partial includes for used functions, e.g. [lodash-after](https://www.npmjs.org/package/lodash.after) for `_.after()`. That would reduce the size of the final module quite a lot.

Maybe even native ES5 functions where possible and allow using optional polyfills when needed to target older browsers?

**Comment by yamalight** [comment]
looking at lodash 3.0, I'm starting to think it might be worth using lodash lazy functions, not native ones!

**Comment by agonbina** [comment]
I think for those using tools like Webpack or Browserify it would be best to replace requiring ```lodash``` with a hash that requires the modularized lodash methods(ex: [lodash.isarray](https://www.npmjs.com/package/lodash.isarray)):
```js
lodash = { 
  isArray: require('lodash.isarray')
}
module.exports = factory( lodash, this)
```
This way when you build you only get the code for the methods used by postal, and it would continue to work in Node.
Of course this needs specifying each modularized method in ```package.json```. What do you think @yamalight & @ifandelse?

**Comment by yamalight** [comment]
@agonbina I think solution with optional DI proposed in discussion of my PR is a better idea since it's more flexible and is not constrained to specific build methods (e.g. browserify, webpack)

**Comment by yamalight** [comment]
Just opened [PR 110](https://github.com/postaljs/postal.js/pull/110).
@ifandelse @Daveawb need some help there :)

**Comment by jdalton** [comment]
lodash v3 has [improved modularity](https://github.com/lodash/lodash/releases/tag/3.0.0). You can now cherry pick methods:
```js
var each = require('lodash/collection/each');
```

**Comment by yamalight** [comment]
@jdalton lodash 2.x had [per method builds](https://www.npmjs.com/browse/keyword/lodash-modularized) as well. although, as I'd already mentioned in [my last PR](https://github.com/postaljs/postal.js/pull/110), swapping whole lodash to the singular methods impacts little to nothing. I'll copy-paste my measurements from PR here:

original:
non-minified: 248K
minified: 67K

mindash with requires() of partial lodash functions:
non-minified: 163K
minified: 64K

mindash with native ES5 functions and ES5-based implementations (PR code basically):
non-minified: 29K
minified: 15K

**Comment by jdalton** [comment]
@yamalight I know 2.4.1 had individual packages (I wrote them) however it had larger dep graphs. v3.x reduces dep graphs at the cost of some duplication. It'd be worth giving v3 a try and trying the `require('lodash/collection/each')` approach (I believe that will give you the smallest browserify result).

That said I believe something is off in your measurements as simple creating a custom build with [lodash-cli](https://www.npmjs.com/package/lodash-cli):
```js
lodash modern include=after,any,bind,clone,debounce,each,filter,isArray,isEmpty,isEqual,isFunction,isNumber,isObject,isString,map,throttle
```

creates a build of lodash that is 6.2kb gzipped.

mindash is basically sacrificing consistency, stability, support, features, & performance for what amounts to something as little as 6kb of code.

**Comment by yamalight** [comment]
@jdalton hm, that's curious. I measured using browserify to compile the whole thing and then used require('lodash.fn') for all the required function. not really sure why it turned out so big. will try with cli build and update here on how it goes.

also, lodash-cli approach while is interesting, would mean that this custom build of lodash has to be served along with the postal itself. since there's no way to just require() it from the npm right?

I still think mindash approach (considering deployment to ES5 environments and/or polyfills) + way to swap mindash for user-defined library (e.g. custom or full lodash, underscore, etc) would work best.

But in the end we'll have to wait and see what @ifandelse thinks about all this stuff since that's his project :)

**Comment by jdalton** [comment]
> also, lodash-cli approach while is interesting, would mean that this custom build of lodash has to be served along with the postal itself. since there's no way to just require() it from the npm right?

The custom build with `lodash-cli` was to sanity check your crazy high file size report. I've seen devs report high sizes before & it turned out to be user error. Check your browserify options, look around I'm sure there's something missing. Also give the `require('lodash/foo/bar')` approach a shot.

> I still think mindash approach

I'd rather trust something thousands use/depend-on, than a cobbled together mindash. You're pushing the support burden on to postal. The JavaScript community goes through cycles more than fashion. The file size obsession & the-sacrificing-of-everything-for-it comes around frequently. It's incredibly naive to assume your mindash is on the same level as lodash and that it's trivial to create something to the quality of lodash.

**Comment by yamalight** [comment]
Tested it with require('lodash/type/fn') approach, here's the data for it:
non-minified: 137K
minified: 64K

Not much difference as you can see.

On the mindash side - I am aware that mindash will never be on the same level as lodash as it doesn't have lazy evaluation, workarounds for older browsers, speed optimizations and other cool things.
But if you take a look at the methods listed in the message above in this ticket that lists all used lodash functions, you'll notice that most of them have native implementations in ES5. Which means that while they might be slower than lodash, they will works just fine.
On top of that, if users can replace mindash with their own lib (e.g. lodash) for speed or compatibility - I can see no problems with removing lodash at all here.

But, once again, that's something for project maintainer to decide.

**Comment by jdalton** [comment]
> Tested it with require('lodash/type/fn') approach, here's the data for it:
non-minified: 137K
minified: 64K
>
> Not much difference as you can see.

The fact that you're not seeing much difference leads me to believe something is off. You should be seeing a significant difference as others have reported big wins when using the `'lodash/foo/bar'` approach.

**Comment by yamalight** [comment]
@jdalton I don't really see how it's possible to use require('lodash/type/fn') in a wrong way. feel free to try yourself: 

1. checkout [my fork](https://github.com/yamalight/postal.js) 
2. switch to branch `lodash-partial` that uses lodash3 function includes
3. compile new version of postal using `npm run build` 
4. create test.js that contains `var postal = require('./lib/postal.js');`
5. assemble test.output.js using browserify by using `browserify test.js > test.output.js`
6. uglify compiled file using `uglifyjs test.output.js > test.min.js`

And check the size.

**Comment by jdalton** [comment]
> I don't really see how it's possible to use require('lodash/type/fn') in a wrong way. feel free to try yourself

Thanks. I'll check it out tonight and see what's up.

**Comment by jdalton** [comment]
Using the [bundle-collapser](https://www.npmjs.com/package/bundle-collapser) browserify plugin, some additional Uglify commands, & [gzip-size](https://www.npmjs.com/package/gzip-size):

```bash
$ browserify test.js -p bundle-collapser/plugin -o bundle.js
$ uglifyjs bundle.js -m -c "comparisons=false,keep_fargs=true,unsafe=true,unsafe_comps=true,warnings=false" -b "beautify=false,ascii-only=true" -o bundle.min.js
```

Also included is replacing the browserify step with [webpack](https://www.npmjs.com/package/webpack):
```bash
webpack --optimize-dedup --optimize-occurence-order test.js bundle.js
```

For the mindash the size is:
```bash
$ gzip-size bundle.min.js # => browserify: 3.74kb; webpack: 3.63kb
```

For the kitchen sink `require('lodash')` the size is
```bash
$ gzip-size bundle.min.js # => browserify: 19.82kb; webpack: 19.71kb
```

For the cherry-pick `require('lodash/foo/bar')` the size is:
```bash
$ gzip-size bundle.min.js # => browserify: 10.04kb; webpack: 9.62kb
```

For the cherry-pick `require('lodash/foo/bar')` that removes `'lodash/lang/clone'` in favor of `'lodash/internal/baseAssign'` & uses internal `'lodash/internal/arraySome'`, `'lodash/internal/arrayEach'`, `'lodash/internal/arrayFilter'`, `'lodash/internal/arrayMap'`, & `lodash.bind`
```bash
$ gzip-size bundle.min.js # => browserify: 7.75kb; webpack: 7.46kb
```

So ~3.8kb difference between lodash & mindash. Which isn't as big a difference considering switching from the kitchen sink to cherry-picking saves more than 12kb.

**Comment by jdalton** [comment]
Opened a pull request #112 to upgrade lodash to v3.

**Comment by yamalight** [comment]
@jdalton whoa, that actually looks very good. Looks like I indeed did not know how to use lodash partials properly - thanks for showing!
I guess my PR becomes quite useless at this point, will close it in favor of lodash-3 one.

**Comment by ifandelse** [comment]
@jdalton @yamalight @agonbina - I seriously appreciate the interest and discussion around this! (As well as your patience with me as it's taken me a few days to catch up on everything.) @jdalton's PR #112  has been merged, and the latest version now contains the custom lodash build alongside the standard postal builds (with an note in the README about this as well). *This* is exactly the kind of thing that continues to draw me out into OSS work - I'm honored for the contributions!

**Comment by jdalton** [comment]
Congrats on bumping 1.0! :tada:

**Comment by yamalight** [comment]
@ifandelse same here! was extremely interesting. 
Not only I got a smaller version of postal.js with updated lodash for my projects. I also learned some nice things about minimizing lodash size / using lodash 3 from @jdalton 
Cannot ask for more from one issue :)
