### ISSUE TITLE
Possible bug in #unsubscribeFor

### ISSUE THREAD

**Issue by estaylorco** [postaljs/postal.js#96]
Please see this thread for reference: https://github.com/postaljs/postal.js/issues/61.

Thank you for adding `unsubscribeFor` at my request.  It would seem, though, that I have encountered a bug.  If the predicate against a `SubscriptionDefinition` is a channel and custom property, `unsubscribeFor` doesn't always seem to actually unsubscribe.

Consider this code:

    /**
     * @method unsubscribeTransients
     * Unsubscribe all transient subscriptions registered with the message bus on the outlet message channel.
     */
    Datepicker.prototype.unsubscribeTransients = function () {
        postal.unsubscribeFor({
                channel: this.calendarNavigator.outletMessageChannel,
                residence: this.kTransient
            });
        };

where `residence` is a custom property added using UnderscoreJS's #extend method on the `SubscriptionDefinition`.

If I comment out the following line

    channel: this.calendarNavigator.outletMessageChannel,

in the predicate, it works fine.

**NOT SO FAST!**

In the one module where I've used `unsubscribeFor`, **the subscriptions are not actually released from memory (and, consequently, not garbage-collected)**.

I don't have this problem, though, when I use my previous technique of pushing the subscriptions into an array.  This works great:

    /*global define*/
    define('mixins/mixin.unregistersubscriptions',
        [
            'underscore'
        ],
        function (
            _
            ) {
            return {
                unregisterSubscriptions: function (subscriptionsArray) {               
                    var subs = subscriptionsArray || this.subscriptions;
                
                    if (!_.isArray(subs)) {
                        return;
                    }
                
                    _.each(subs, function (sub) {
                        sub.unsubscribe();
                        sub.callback = null;
                    });
                
                    subs = null;                
                }
            };
        });

**Comment by ifandelse** [comment]
Just checking in - still having issues here?
